version: "3.7"

services:
  build-application:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    environment:
      - INSTALL_PATH=/builder/install
    volumes:
      - ./:/builder:rw
      - ./install:/builder/install:rw
    working_dir: /builder
    entrypoint: /builder/scripts/run-all.sh
